export const SET_AUTO_VERZEKERING_TYPE = "SET_AUTO_VERZEKERING_TYPE";
export const SET_AUTO_VERZEKERING_TYPE_FETCHED = "SET_AUTO_VERZEKERING_TYPE_FETCHED";

export const SET_CLAIMS = "SET_CLAIMS";
export const DELETE_CLAIM = "DELETE_CLAIM";
export const EDIT_CLAIM = "EDIT_CLAIM";
export const ADD_CLAIM = "ADD_CLAIM";
export const SET_CLAIMS_FETCHED = "SET_CLAIMS_FETCHED";